<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Fiap.Workshop.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cpf.Cnpj" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fiap.Workshop.Domain\Fiap.Workshop.Domain.csproj" />
  </ItemGroup>

</Project>
