<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Fiap.Workshop.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="10.0.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fiap.Workshop.Application\Fiap.Workshop.Application.csproj" />
    <ProjectReference Include="..\Fiap.Workshop.Infrastructure\Fiap.Workshop.Infrastructure.csproj" />
  </ItemGroup>

</Project>
